name: BlockDropsRandomizer
version: 1.0.1
main: me.rilecraft.blockdropsrandomizer.BlockDropsRandomizer
api-version: 1.13
authors: [ RileCraft ]
description: A complete block drops randomizer.
commands:
  BDR:
    description: Main Command of Block Randomization Plugin.