# Blocks Drops Randomizer Configuration File.
# Author: RileCraft :D
# Version: 1.0.0

BDR:
  enabled: true #Enables/Disables the plugin.
  blacklistedBlocks:
    #- BEDROCK # Blacklists Bedrock from being added in random shuffle. FixedList ignores this.
  randomizeEachDrop: false # Whether to drop something random each time you break the same block or have a fixed item that will drop always when you break that block.
  allowExplosionDrops: false # Whether to also randomize or fix item drops if the block is broken by a explosion.

  FixedList:
    items: # You can have to use the format below.
      #STONE: # MUST BE IN CAPITALS!
          #- DIRT:2
          #- COBBLESTONE:1 # Mining Stone will always drop 2 dirt and 1 cobblestone.